# Generated by Django 5.2 on 2025-04-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customPrebuilts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steam_store_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Spec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spec", models.IntegerField(unique=True)),
                ("description", models.CharField(verbose_name=20)),
            ],
        ),
        migrations.AddField(
            model_name="partscpu",
            name="series",
            field=models.CharField(default="Unknown", max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="GameSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spec", models.IntegerField()),
                ("geforce", models.CharField(blank=True, max_length=50)),
                ("radeon", models.CharField(blank=True, max_length=50)),
                ("arc", models.CharField(blank=True, max_length=50)),
                ("fps", models.IntegerField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=50, null=True)),
                ("preset", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customPrebuilts.game",
                    ),
                ),
            ],
        ),
    ]
