# Generated by Django 5.2 on 2025-04-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customPrebuilts", "0002_game_spec_partscpu_series_gamespec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spec",
            name="description",
            field=models.CharField(max_length=20),
        ),
    ]
